# Generated by Django 4.2.30 on 2026-07-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeitem',
            name='category',
            field=models.CharField(choices=[('HOT', 'Hot Coffee'), ('COLD', 'Cold Coffee'), ('SNACK', 'Snacks')], default='HOT', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI')], default='CASH', max_length=10),
        ),
    ]
